const VOCAB_A2 = [
["die Angst","fear"],
["abschließen","to lock"],
["die Ahnung","idea / clue"],
["aktiv","active"],
["aktuell","current / up to date"],
["als","as / when / than"],
["die Ampel","traffic light"],
["ansehen","to look at"],
["ändern","to change"],
["anders","different(ly)"],
["der Anzug","suit"],
["die Apotheke","pharmacy"],
["der Apparat","device / apparatus"],
["sich ärgern","to be annoyed"],
["der Artikel","article"],
["auspacken","to unpack"],
["sich ausruhen","to rest"],
["aufräumen","to tidy up"],
["außer","except for"],
["außerdem","besides / in addition"],
["außerhalb","outside of"],
["aussprechen","to pronounce"],
["aufregend","exciting"],
["aufpassen","to pay attention"],
["aufmachen","to open"],
["die Ausbildung","vocational training"],
["die Ausstellung","exhibition"],
["austragen","to deliver (newspapers)"],
["ausgeben","to spend (money)"],
["ausgehen","to go out"],
["beantworten","to answer (a question)"],
["der Babysitter","babysitter"],
["sich bedanken","to say thank you"],
["sich beeilen","to hurry"],
["beenden","to finish / end"],
["die Band","band"],
["begründen","to give reasons"],
["der Basketball","basketball"],
["basteln","to do crafts"],
["bauen","to build"],
["beliebt","popular"],
["bequem","comfortable"],
["die Baustelle","construction site"],
["beraten","to advise"],
["der Berg","mountain"],
["berichten","to report"],
["sich bewerben","to apply (for a job)"],
["die Bewerbung","job application"],
["berühmt","famous"],
["bewölkt","cloudy"],
["der Bescheid","notice (Bescheid sagen: to inform)"],
["die Wolke","cloud"],
["beschreiben","to describe"],
["sich beschweren","to complain"],
["besonders","especially"],
["bestätigen","to confirm"],
["bestehen","to pass (an exam)"],
["die Bibliothek","library"],
["das Blatt","sheet / leaf"],
["bleiben","to stay"],
["der Besuch","visit"],
["blöd","stupid / dumb"],
["der Blog","blog"],
["blond","blond"],
["bunt","colorful"],
["das Büro","office"],
["die Bluse","blouse"],
["die Bohne","bean"],
["braten","to fry / roast"],
["die Cafeteria","cafeteria"],
["chatten","to chat (online)"],
["die Chefin","boss (female)"],
["die Brille","glasses"],
["der Club","club"],
["der Comic","comic"],
["die Creme","cream / lotion"],
["die Brücke","bridge"],
["buchen","to book"],
["dabei sein","to be there / take part"],
["dafür","for it / in favor"],
["dagegen","against it"],
["damals","back then"],
["drüben","over there"],
["danke","thank you"],
["dass","that (conjunction)"],
["die Datei","file (computer)"],
["dumm","stupid"],
["denken","to think"],
["dunkel","dark"],
["dünn","thin"],
["deshalb","therefore / that's why"],
["deutlich","clear(ly)"],
["dick","fat / thick"],
["das Ding","thing"],
["direkt","direct(ly)"],
["diskutieren","to discuss"],
["doch","yes it is / though"],
["das E-Book","e-book"],
["egal","doesn't matter"],
["dringend","urgent"],
["drinnen","inside"],
["der Ehepartner","spouse"],
["eigen","own"],
["eigentlich","actually"],
["das Eis","ice cream / ice"],
["einige","some / a few"],
["endlich","finally"],
["das Einkaufszentrum","shopping mall"],
["einpacken","to pack / wrap"],
["das Erdgeschoss","ground floor"],
["die Erfahrung","experience"],
["sich erinnern","to remember"],
["erkältet sein","to have a cold"],
["sich eintragen","to sign up / register"],
["einverstanden sein","to agree"],
["erlaubt","allowed"],
["die Erlaubnis","permission"],
["die Ermäßigung","discount"],
["einziehen","to move in"],
["erreichen","to reach"],
["erst","only / not until / first"],
["fast","almost"],
["faul","lazy"],
["der Feierabend","end of the workday"],
["das Fenster","window"],
["die Ferien","school holidays"],
["das Fach","subject (school)"],
["der Fernseher","TV set"],
["das Fest","festival / celebration"],
["das Festival","festival"],
["fett","fatty / fat"],
["der Fahrplan","timetable"],
["fallen","to fall"],
["der Fan","fan"],
["fantastisch","fantastic"],
["fit sein","to be fit"],
["die Freundin","friend (female) / girlfriend"],
["freundlich","friendly"],
["fleißig","hard-working"],
["frisch","fresh"],
["froh","glad"],
["der Flohmarkt","flea market"],
["der Flug","flight"],
["der Fluss","river"],
["der Fotoapparat","camera"],
["sich fühlen","to feel"],
["fotografieren","to photograph"],
["früh","early"],
["der Führerschein","driver's license"],
["die Fundsachen","lost property"],
["furchtbar","terrible"],
["freiwillig","voluntary"],
["der Freiwillige","volunteer"],
["die Gabel","fork"],
["ganz","whole / quite"],
["die Garage","garage"],
["die Geschichte","history / story"],
["das Geschirr","dishes"],
["das Gesicht","face"],
["gefährlich","dangerous"],
["das Gegenteil","opposite"],
["gegenüber","opposite / across from"],
["gesund","healthy"],
["das Gehalt","salary"],
["die Gesundheit","health"],
["die Geldbörse","wallet / purse"],
["genau","exact(ly)"],
["das Gewitter","thunderstorm"],
["die Gitarre","guitar"],
["genug","enough"],
["das Gerät","device"],
["das Gericht","dish (food) / court"],
["die Grippe","flu"],
["hallo","hello"],
["das Heft","notebook / exercise book"],
["heiß","hot"],
["die Heizung","heating"],
["der Hals","neck / throat"],
["das Hemd","shirt"],
["der Hamburger","hamburger"],
["der Herr","Mr. / gentleman"],
["das Handtuch","towel"],
["herstellen","to produce"],
["hängen","to hang"],
["herunterladen","to download"],
["hart","hard"],
["hässlich","ugly"],
["die Hauptstadt","capital city"],
["der Haushalt","household"],
["der Himmel","sky"],
["das Instrument","instrument"],
["hinter","behind"],
["intelligent","intelligent"],
["das Interesse","interest"],
["sich interessieren","to be interested in"],
["hoffen","to hope"],
["interessant","interesting"],
["das Interview","interview"],
["die Homepage","homepage"],
["ja","yes"],
["die Hose","trousers / pants"],
["husten","to cough"],
["die Jeans","jeans"],
["jemand","someone"],
["joggen","to jog"],
["die Idee","idea"],
["der Kaffee","coffee"],
["die Insel","island"],
["der Kalender","calendar"],
["die Kirche","church"],
["kalt","cold"],
["klappen","to work out (go well)"],
["die Kamera","camera"],
["das Klavier","piano"],
["das Kleid","dress"],
["der Käse","cheese"],
["die Katze","cat"],
["klug","smart / clever"],
["das Kaufhaus","department store"],
["kein","no / none"],
["der Keller","basement / cellar"],
["die Kollegin","colleague (female)"],
["komisch","funny / strange"],
["die Kenntnisse","knowledge / skills"],
["die Kette","necklace / chain"],
["der Kontakt","contact"],
["kontrollieren","to check / inspect"],
["das Konzert","concert"],
["kündigen","to quit / cancel (a contract)"],
["der Körper","body"],
["die Kosmetik","cosmetics"],
["die Kunst","art"],
["kostenlos","free of charge"],
["das Krankenhaus","hospital"],
["die Krankenkasse","health insurance"],
["die Krankheit","illness"],
["der Kredit","loan / credit"],
["die Kreuzung","intersection / crossroads"],
["die Lampe","lamp"],
["die Landschaft","landscape"],
["lange","for a long time"],
["der Krimi","crime story / thriller"],
["langweilig","boring"],
["der Laptop","laptop"],
["kühl","cool"],
["lassen","to let / leave"],
["die Kultur","culture"],
["die Kundin","customer (female)"],
["leer","empty"],
["der Link","link"],
["der Löffel","spoon"],
["die Lüge","lie (untruth)"],
["lügen","to lie (tell untruth)"],
["leidtun","to be sorry"],
["leihen","to lend / borrow"],
["die Lust","desire (Lust haben: to feel like)"],
["der Magen","stomach"],
["die Mailbox","voicemail"],
["das Mal","time (occasion)"],
["malen","to paint"],
["lieb","dear / kind"],
["die Mannschaft","team (sports)"],
["der Mantel","coat"],
["der Markt","market"],
["manchmal","sometimes"],
["manche","some"],
["liefern","to deliver"],
["das Medikament","medicine"],
["das Mittel","means / remedy"],
["das Mobiltelefon","mobile phone"],
["meinen","to think / mean"],
["die Meinung","opinion"],
["die Mode","fashion"],
["modern","modern"],
["meistens","mostly / usually"],
["die Menge","amount / crowd"],
["merken","to notice"],
["die Messe","trade fair"],
["der Motor","engine"],
["das Messer","knife"],
["der Motorroller","scooter"],
["der Müll","garbage / trash"],
["das Museum","museum"],
["die Musik","music"],
["mindestens","at least"],
["die Mütze","cap / beanie"],
["der Mitarbeiter","employee / co-worker"],
["das Mittagessen","lunch"],
["der Nachbar","neighbor"],
["die Nachbarin","neighbor (female)"],
["die Nachricht","message / news"],
["die Note","grade / mark"],
["die Nähe","vicinity (in der Nähe: nearby)"],
["notieren","to note down"],
["nass","wet"],
["die Notiz","note"],
["die Natur","nature"],
["notwendig","necessary"],
["natürlich","of course / natural"],
["die Nudel","noodle / pasta"],
["neben","next to"],
["nebenan","next door"],
["neblig","foggy"],
["nützlich","useful"],
["nein","no"],
["nennen","to name / call"],
["offen","open"],
["nervös","nervous"],
["nett","nice / kind"],
["das Ohr","ear"],
["online","online"],
["niemand","nobody"],
["die Orange","orange"],
["nirgends","nowhere"],
["organisieren","to organize"],
["das Paar","couple / pair"],
["ein paar","a few"],
["packen","to pack"],
["das Pferd","horse"],
["die Pflanze","plant"],
["die Pizza","pizza"],
["das Plakat","poster / placard"],
["planen","to plan"],
["das Paket","parcel / package"],
["das Parfüm","perfume"],
["der Park","park"],
["parken","to park"],
["plötzlich","suddenly"],
["die Portion","portion"],
["das Poster","poster"],
["die Postkarte","postcard"],
["praktisch","practical"],
["passen","to fit"],
["preiswert","inexpensive / good value"],
["privat","private"],
["pro","per"],
["probieren","to try / taste"],
["passieren","to happen"],
["das Passwort","password"],
["recht haben","to be right"],
["das Programm","program"],
["das Projekt","project"],
["reden","to talk"],
["prüfen","to check / test"],
["der Pullover","sweater"],
["putzen","to clean"],
["reich","rich"],
["der Reifen","tire"],
["die Reihe","row / series"],
["die Reinigung","dry cleaner's"],
["die Qualität","quality"],
["das Quiz","quiz"],
["das Radio","radio"],
["raten","to guess / advise"],
["reiten","to ride (a horse)"],
["das Rathaus","town hall"],
["das Rätsel","puzzle / riddle"],
["renovieren","to renovate"],
["der Rentner","pensioner / retiree"],
["rechnen","to calculate"],
["reservieren","to reserve"],
["der Rest","rest / remainder"],
["das Rezept","recipe / prescription"],
["der Satz","sentence"],
["sauber","clean"],
["sauer","sour / annoyed"],
["schade","a pity / shame"],
["schädlich","harmful"],
["schaffen","to manage / accomplish"],
["sammeln","to collect"],
["das Rind","beef / cattle"],
["der Ring","ring"],
["der Rock","skirt"],
["romantisch","romantic"],
["die Rose","rose"],
["der Rücken","back (body)"],
["scharf","spicy / sharp"],
["der Rucksack","backpack"],
["rufen","to call / shout"],
["schenken","to give (as a gift)"],
["die Ruhe","quiet / calm"],
["die Schere","scissors"],
["rund","round"],
["der Rundgang","tour / walkaround"],
["die Sache","thing / matter"],
["das Schiff","ship"],
["schimpfen","to scold / complain"],
["schrecklich","terrible"],
["der Schirm","umbrella"],
["das Schlafzimmer","bedroom"],
["schlimm","bad / serious"],
["das Schloss","castle / lock"],
["schriftlich","in writing"],
["schwach","weak"],
["schwanger","pregnant"],
["das Schwein","pig / pork"],
["schwierig","difficult"],
["der Schmerz","pain"],
["schmutzig","dirty"],
["der Schnee","snow"],
["sich schneiden","to cut oneself"],
["die See","sea"],
["schneien","to snow"],
["die Schokolade","chocolate"],
["die Seife","soap"],
["an sein","to be on"],
["aus sein","to be off"],
["auf sein","to be open"],
["weg sein","to be gone"],
["zu sein","to be closed"],
["sonnig","sunny"],
["sonst","otherwise"],
["spannend","exciting / thrilling"],
["sparen","to save (money)"],
["der Spaß","fun"],
["die Seite","page / side"],
["selbst","self / even"],
["die Sendung","TV program / broadcast"],
["spazieren gehen","to go for a walk"],
["der Spaziergang","walk / stroll"],
["sich setzen","to sit down"],
["sicher","safe / sure"],
["speichern","to save (a file)"],
["singen","to sing"],
["die Situation","situation"],
["das Spiel","game"],
["der Ski","ski"],
["sportlich","sporty / athletic"],
["der Sportplatz","sports field"],
["sogar","even"],
["die Sprechstunde","office hours / consultation"],
["streng","strict"],
["der Stress","stress"],
["der Stadtplan","city map"],
["stressig","stressful"],
["der Star","star (celebrity)"],
["das Stück","piece"],
["stark","strong"],
["stattfinden","to take place"],
["sterben","to die"],
["der Stuhl","chair"],
["der Stiefel","boot"],
["super","great / super"],
["der Supermarkt","supermarket"],
["die Suppe","soup"],
["surfen","to surf"],
["der Stift","pen"],
["das Stipendium","scholarship"],
["das Stockwerk","floor / story"],
["stören","to disturb"],
["der Strand","beach"],
["süß","sweet / cute"],
["die Süßigkeiten","sweets / candy"],
["sympathisch","likeable"],
["sich streiten","to argue"],
["das Tablet","tablet"],
["die Tafel","(black)board"],
["das Taschengeld","pocket money"],
["die Tasse","cup"],
["tauschen","to swap / exchange"],
["das Team","team"],
["das Tier","animal"],
["der Tipp","tip / hint"],
["der Titel","title"],
["toll","great"],
["der Topf","pot"],
["die Torte","cake / gateau"],
["total","totally"],
["die Tour","tour"],
["der Tourist","tourist"],
["teilen","to share / divide"],
["teilnehmen","to take part"],
["tief","deep"],
["tragen","to carry / wear"],
["trainieren","to train / work out"],
["der Teller","plate"],
["das Tennis","tennis"],
["das Training","training"],
["der Traum","dream"],
["das Theater","theater"],
["träumen","to dream"],
["traurig","sad"],
["umsteigen","to change (trains)"],
["trocken","dry"],
["das T-Shirt","T-shirt"],
["die Tür","door"],
["typisch","typical"],
["der Umzug","move (house) / parade"],
["unbedingt","absolutely / definitely"],
["der Unfall","accident"],
["die Universität","university"],
["sich unterhalten","to chat / converse"],
["üben","to practice"],
["über","over / about"],
["überall","everywhere"],
["die Unterkunft","accommodation"],
["übermorgen","the day after tomorrow"],
["unternehmen","to do / undertake (an activity)"],
["der Unterschied","difference"],
["übersetzen","to translate"],
["untersuchen","to examine"],
["verlieren","to lose"],
["verabredet sein","to have an appointment / date"],
["verbieten","to forbid"],
["verpassen","to miss (a train, a chance)"],
["verreisen","to go on a trip"],
["verschieben","to postpone"],
["verschieden","different / various"],
["vereinbaren","to arrange / agree on"],
["die Verspätung","delay"],
["vergessen","to forget"],
["versuchen","to try"],
["vergleichen","to compare"],
["der Verkehr","traffic"],
["das Verkehrsmittel","means of transport"],
["sich verletzen","to injure oneself"],
["der Vertrag","contract"],
["der Vogel","bird"],
["voll","full"],
["der Volleyball","volleyball"],
["sich verlieben","to fall in love"],
["vorbei","over / past"],
["die Wäsche","laundry"],
["vorbereiten","to prepare"],
["vorgestern","the day before yesterday"],
["vorher","before / previously"],
["die Webseite","website"],
["vorne","at the front"],
["wechseln","to change / exchange"],
["der Vorschlag","suggestion"],
["wecken","to wake (someone) up"],
["vorsichtig","careful"],
["weg","away / gone"],
["wegfahren","to drive away"],
["vorwärts","forward"],
["weggehen","to go away / leave"],
["wach","awake"],
["der Wagen","car / wagon"],
["weglaufen","to run away"],
["wählen","to choose / dial / vote"],
["wegnehmen","to take away"],
["wegwerfen","to throw away"],
["wahr","true"],
["der Weg","way / path"],
["wahrscheinlich","probably"],
["wegen","because of"],
["der Wald","forest"],
["warm","warm"],
["weich","soft"],
["weil","because"],
["warum","why"],
["was","what"],
["weinen","to cry"],
["wenigstens","at least"],
["wenn","if / when"],
["wer","who"],
["windig","windy"],
["wirklich","really"],
["der Witz","joke"],
["witzig","funny / witty"],
["wo","where"],
["woher","where from"],
["wohin","where to"],
["die Werkstatt","garage / workshop"],
["der Wettbewerb","competition"],
["das Wohnzimmer","living room"],
["wie","how"],
["wieder","again"],
["der Workshop","workshop"],
["der Wunsch","wish"],
["wünschen","to wish"],
["die Wurst","sausage"],
["die Zahl","number"],
["der Zahn","tooth"],
["zeichnen","to draw"],
["zuletzt","lastly / finally"],
["zumachen","to close"],
["zeigen","to show"],
["die Zeitschrift","magazine"],
["zurückfahren","to drive back"],
["das Zelt","tent"],
["das Zentrum","center"],
["zurückgeben","to give back"],
["der Zettel","note / slip of paper"],
["zurückgehen","to go back"],
["das Zeugnis","report card / certificate"],
["zurückkommen","to come back"],
["das Ziel","goal / destination"],
["der Zirkus","circus"],
["die Zitrone","lemon"],
["der Zoo","zoo"],
["der Zucker","sugar"],
["zuerst","first / at first"],
["zuhören","to listen (to)"],
["die Tante","aunt"],
["der Onkel","uncle"],
["der Enkel","grandchild / grandson"],
["anstrengend","exhausting / strenuous"],
["ausverkauft","sold out"],
["backen","to bake"],
["die Bedienung","service / waiter"],
["tanken","to fill up (fuel)"],
["die Tankstelle","gas station"],
["der Stau","traffic jam"],
["die Panne","breakdown"],
["die Fähre","ferry"],
["der Hafen","harbor / port"],
["die Grenze","border"],
["die Linie","line (bus/tram number)"],
["die Richtung","direction"],
["der Aufenthalt","stay / stopover"],
["hin und zurück","there and back / round trip"],
["die Tablette","pill / tablet"],
["der Zahnarzt","dentist"],
["die Versicherung","insurance"],
["der Pfeffer","pepper"],
["die Marmelade","jam"],
["der Joghurt","yogurt"],
["die Sahne","cream (whipped)"],
["anprobieren","to try on"],
["der Gürtel","belt"],
["die Socke","sock"],
["die Terrasse","terrace / patio"],
["der Quadratmeter","square meter"],
["der Arbeitgeber","employer"],
["der Arbeitnehmer","employee"],
["der Lebenslauf","CV / résumé"],
["der Anhang","attachment"],
["ausdrucken","to print out"],
["löschen","to delete"],
["abbiegen","to turn (off a road)"],
["ziehen","to pull"],
["klingeln","to ring (bell)"],
["begrüßen","to greet"],
["wiegen","to weigh"],
["arm","poor"],
["eng","tight / narrow"],
["gemütlich","cozy"],
["hübsch","pretty"],
["niedrig","low"],
["schlank","slim"],
["danach","afterwards"],
["davor","before that"],
["hoffentlich","hopefully"],
["kaum","hardly / barely"],
["nachher","later / afterwards"],
["trotzdem","nevertheless / anyway"],
["unterwegs","on the way / out and about"],
["gleichfalls","likewise / same to you"],
["der Nebel","fog"],
["der Sturm","storm"],
["die Temperatur","temperature"]
];
