const VOCAB = [
["die Ankunft","arrival"],
["ab","from (a time/point)"],
["aber","but"],
["abfahren","to depart"],
["die Abfahrt","departure"],
["abgeben","to hand in"],
["abholen","to pick up"],
["der Absender","sender"],
["Achtung","attention / caution"],
["die Adresse","address"],
["alle","all / everyone"],
["allein","alone"],
["also","so / therefore"],
["alt","old"],
["das Alter","age"],
["an","at / on"],
["das Angebot","offer"],
["andere","other"],
["anfangen","to begin"],
["der Anfang","beginning"],
["anklicken","to click on"],
["ankommen","to arrive"],
["ankreuzen","to tick / mark"],
["anmachen","to turn on"],
["anmelden","to register"],
["die Anmeldung","registration"],
["die Anrede","form of address"],
["anrufen","to call (phone)"],
["der Anruf","phone call"],
["anbieten","to offer"],
["die Ansage","announcement"],
["der Anschluss","connection"],
["antworten","to answer"],
["die Antwort","answer"],
["die Anzeige","advertisement"],
["anziehen","to put on (clothes)"],
["das Apartment","apartment"],
["der Apfel","apple"],
["der Appetit","appetite"],
["arbeiten","to work"],
["die Arbeit","work"],
["arbeitslos","unemployed"],
["der Arbeitsplatz","workplace"],
["der Arm","arm"],
["der Arzt","doctor"],
["auch","also / too"],
["auf","on / onto"],
["die Aufgabe","task / exercise"],
["aufhören","to stop"],
["aufstehen","to get up"],
["der Aufzug","elevator"],
["das Auge","eye"],
["aus","from / out of"],
["der Ausflug","excursion / trip"],
["ausfüllen","to fill out"],
["der Ausgang","exit"],
["die Auskunft","information (desk)"],
["das Ausland","foreign country / abroad"],
["der Ausländer","foreigner"],
["ausländisch","foreign"],
["ausmachen","to turn off"],
["die Aussage","statement"],
["aussehen","to look / appear"],
["aussteigen","to get off / out"],
["der Ausweis","ID card"],
["ausziehen","to take off / move out"],
["das Auto","car"],
["die Autobahn","highway"],
["der Automat","vending machine"],
["automatisch","automatic"],
["abfliegen","to fly off / depart (plane)"],
["der Abflug","flight departure"],
["das Baby","baby"],
["die Bäckerei","bakery"],
["das Bad","bathroom / bath"],
["baden","to bathe"],
["die Bahn","train / railway"],
["der Bahnhof","train station"],
["der Bahnsteig","platform"],
["bald","soon"],
["der Balkon","balcony"],
["die Banane","banana"],
["die Bank","bank / bench"],
["bar","in cash"],
["der Bauch","belly / stomach"],
["der Baum","tree"],
["der Beamte","civil servant"],
["bedeuten","to mean"],
["beginnen","to begin"],
["bei","at / near / with"],
["beide","both"],
["das Bein","leg"],
["das Beispiel","example"],
["zum Beispiel","for example"],
["bekannt","well-known"],
["der Bekannte","acquaintance"],
["bekommen","to get / receive"],
["benutzen","to use"],
["brauchen","to need"],
["der Beruf","profession / job"],
["breit","wide"],
["besetzt","occupied / busy"],
["der Brief","letter (mail)"],
["besichtigen","to visit / sightsee"],
["die Briefmarke","postage stamp"],
["besser","better"],
["bringen","to bring"],
["beste","best"],
["das Brot","bread"],
["bestellen","to order"],
["das Brötchen","bread roll"],
["besuchen","to visit"],
["der Bruder","brother"],
["das Bett","bed"],
["das Buch","book"],
["bezahlen","to pay"],
["der Buchstabe","letter (alphabet)"],
["das Bier","beer"],
["buchstabieren","to spell"],
["das Bild","picture"],
["der Bus","bus"],
["billig","cheap"],
["die Butter","butter"],
["die Birne","pear"],
["das Café","café"],
["bis","until"],
["die CD","CD"],
["der Chef","boss"],
["bisschen","a little bit"],
["circa","approximately"],
["bitte","please"],
["die Bitte","request"],
["der Computer","computer"],
["bitten","to ask / request"],
["bitter","bitter"],
["da","there / since"],
["die Dame","lady"],
["der Bleistift","pencil"],
["daneben","next to it"],
["der Blick","view / glance"],
["danken","to thank"],
["die Blume","flower"],
["der Dank","thanks"],
["der Bogen","sheet / form"],
["dann","then"],
["böse","angry / evil"],
["das Datum","date"],
["dauern","to last / take (time)"],
["der Eingang","entrance"],
["denn","because / then"],
["einkaufen","to shop"],
["die Disco","disco"],
["einladen","to invite"],
["die Einladung","invitation"],
["einmal","once"],
["einsteigen","to get in / board"],
["der Eintritt","admission / entry"],
["das Einzelzimmer","single room"],
["die Eltern","parents"],
["die E-Mail","email"],
["der Empfänger","recipient"],
["empfehlen","to recommend"],
["enden","to end"],
["das Ende","end"],
["der Doktor","doctor"],
["das Doppelzimmer","double room"],
["das Dorf","village"],
["dort","there"],
["draußen","outside"],
["drucken","to print"],
["der Drucker","printer"],
["drücken","to push / press"],
["durch","through"],
["die Durchsage","announcement (PA)"],
["dürfen","to be allowed to"],
["der Durst","thirst"],
["duschen","to shower"],
["entschuldigen","to excuse"],
["die Dusche","shower"],
["die Entschuldigung","apology / excuse me"],
["das Ergebnis","result"],
["die Ecke","corner"],
["erklären","to explain"],
["die Ehefrau","wife"],
["erlauben","to allow"],
["der Erwachsene","adult"],
["erzählen","to tell (a story)"],
["essen","to eat"],
["das Ei","egg"],
["das Essen","food / meal"],
["eilig","in a hurry"],
["einfach","simple / easy"],
["fahren","to drive / go"],
["der Ehemann","husband"],
["der Fahrer","driver"],
["die Fahrkarte","ticket (transport)"],
["das Fahrrad","bicycle"],
["der Flughafen","airport"],
["falsch","wrong / false"],
["das Flugzeug","airplane"],
["die Familie","family"],
["das Formular","form (document)"],
["der Familienname","family name"],
["das Foto","photo"],
["der Familienstand","marital status"],
["fragen","to ask"],
["die Farbe","color"],
["die Frage","question"],
["das Fax","fax"],
["die Frau","woman / wife / Mrs."],
["die Feier","celebration"],
["frei","free"],
["feiern","to celebrate"],
["die Freizeit","free time"],
["fehlen","to be missing"],
["fremd","foreign / strange"],
["der Fehler","mistake"],
["freuen","to be glad"],
["fernsehen","to watch TV"],
["der Freund","friend / boyfriend"],
["fertig","finished / ready"],
["früher","earlier / in the past"],
["das Feuer","fire"],
["frühstücken","to have breakfast"],
["das Fieber","fever"],
["das Frühstück","breakfast"],
["der Film","film / movie"],
["die Führung","guided tour"],
["finden","to find"],
["der Fuß","foot"],
["der Fußball","football / soccer"],
["die Firma","company"],
["der Fisch","fish"],
["der Garten","garden"],
["die Flasche","bottle"],
["der Gast","guest"],
["das Fleisch","meat"],
["geben","to give"],
["fliegen","to fly"],
["geboren","born"],
["das Geburtsjahr","year of birth"],
["der Geburtsort","place of birth"],
["das Glück","luck / happiness"],
["der Geburtstag","birthday"],
["glücklich","happy"],
["gefallen","to please / be liked"],
["gegen","against"],
["gehen","to go / walk"],
["Grad","degree (temperature)"],
["gehören","to belong to"],
["gratulieren","to congratulate"],
["das Geld","money"],
["grillen","to barbecue / grill"],
["groß","big / tall"],
["die Größe","size"],
["die Großeltern","grandparents"],
["die Großmutter","grandmother"],
["der Großvater","grandfather"],
["die Gruppe","group"],
["der Gruß","greeting"],
["das Gemüse","vegetables"],
["das Gepäck","luggage"],
["gerade","just now / straight"],
["geradeaus","straight ahead"],
["gerne","gladly / with pleasure"],
["der Glückwunsch","congratulations"],
["das Geschäft","shop / business"],
["das Geschenk","present / gift"],
["die Geschwister","siblings"],
["gültig","valid"],
["das Gespräch","conversation"],
["günstig","cheap / favorable"],
["gestern","yesterday"],
["gut","good"],
["gestorben","deceased"],
["das Getränk","drink / beverage"],
["das Haar","hair"],
["das Gewicht","weight"],
["haben","to have"],
["gewinnen","to win"],
["das Hähnchen","chicken (food)"],
["das Glas","glass"],
["die Halle","hall"],
["glauben","to believe"],
["halten","to hold / stop"],
["gleich","right away / same"],
["die Haltestelle","(bus) stop"],
["das Gleis","track / platform"],
["die Hand","hand"],
["das Handy","mobile phone"],
["das Haus","house"],
["immer","always"],
["die Hausaufgabe","homework"],
["in","in"],
["die Hausfrau","housewife"],
["die Information","information"],
["der Hausmann","househusband"],
["international","international"],
["das Internet","internet"],
["die Heimat","home country / homeland"],
["heiraten","to marry"],
["die Jacke","jacket"],
["jeder","every / each"],
["heißen","to be called"],
["jetzt","now"],
["der Job","job"],
["helfen","to help"],
["der Jugendliche","teenager / youth"],
["hell","bright / light"],
["der Herd","stove"],
["jung","young"],
["der Junge","boy"],
["herzlich","warm / cordial"],
["kaputt","broken"],
["heute","today"],
["die Karte","card / map"],
["hier","here"],
["die Hilfe","help"],
["die Kartoffel","potato"],
["hinten","at the back"],
["die Kasse","checkout / cash desk"],
["das Hobby","hobby"],
["kaufen","to buy"],
["hoch","high"],
["kennen","to know (someone)"],
["die Hochzeit","wedding"],
["kennenlernen","to get to know"],
["holen","to fetch / get"],
["das Kind","child"],
["hören","to hear / listen"],
["der Kindergarten","kindergarten"],
["das Hotel","hotel"],
["das Kino","cinema"],
["der Hund","dog"],
["der Kiosk","kiosk"],
["der Hunger","hunger"],
["klar","clear / of course"],
["die Kreditkarte","credit card"],
["die Klasse","class"],
["lang","long"],
["die Kleidung","clothing"],
["langsam","slow"],
["klein","small"],
["laufen","to run / walk"],
["kochen","to cook"],
["laut","loud"],
["der Koffer","suitcase"],
["leben","to live"],
["der Kollege","colleague"],
["das Leben","life"],
["kommen","to come"],
["die Lebensmittel","groceries"],
["können","can / to be able to"],
["ledig","single / unmarried"],
["das Konto","bank account"],
["legen","to lay / put"],
["der Kopf","head"],
["der Lehrer","teacher"],
["kosten","to cost"],
["leicht","easy / light"],
["krank","sick / ill"],
["leider","unfortunately"],
["kriegen","to get"],
["leise","quiet / soft"],
["die Küche","kitchen"],
["lernen","to learn"],
["der Kuchen","cake"],
["lesen","to read"],
["der Kugelschreiber","ballpoint pen"],
["letzte","last"],
["der Kühlschrank","fridge"],
["die Leute","people"],
["kulturell","cultural"],
["das Licht","light"],
["sich kümmern","to take care of"],
["lieben","to love"],
["der Kunde","customer"],
["lieber","rather / preferably"],
["der Kurs","course"],
["Lieblings-","favorite (prefix)"],
["kurz","short"],
["das Lied","song"],
["liegen","to lie / be located"],
["lachen","to laugh"],
["links","left"],
["der Laden","shop / store"],
["der Lkw","truck"],
["das Lokal","pub / restaurant"],
["das Land","country"],
["die Lösung","solution"],
["möglich","possible"],
["lustig","funny"],
["der Moment","moment"],
["morgen","tomorrow"],
["müde","tired"],
["der Mund","mouth"],
["müssen","must / to have to"],
["die Mutter","mother"],
["machen","to make / do"],
["das Mädchen","girl"],
["man","one / you (in general)"],
["der Mann","man / husband"],
["männlich","male"],
["die Maschine","machine"],
["nach","after / to (a place)"],
["das Meer","sea"],
["nächste","next"],
["der Name","name"],
["nehmen","to take"],
["neu","new"],
["mehr","more"],
["meiste","most"],
["der Mensch","human / person"],
["nicht","not"],
["mieten","to rent"],
["nichts","nothing"],
["die Miete","rent"],
["nie","never"],
["noch","still / yet"],
["normal","normal"],
["die Nummer","number"],
["nur","only"],
["oben","above / upstairs"],
["die Milch","milk"],
["mit","with"],
["mitbringen","to bring along"],
["mitkommen","to come along"],
["mitmachen","to join in"],
["das Obst","fruit"],
["mitnehmen","to take along"],
["oder","or"],
["die Mitte","middle"],
["öffnen","to open"],
["die Möbel","furniture"],
["oft","often"],
["ohne","without"],
["möchten","would like"],
["mögen","to like"],
["das Öl","oil"],
["die Oma","grandma"],
["der Opa","grandpa"],
["der Raum","room / space"],
["die Ordnung","order / tidiness"],
["die Rechnung","bill / invoice"],
["der Ort","place"],
["rechts","right"],
["regnen","to rain"],
["der Regen","rain"],
["der Reis","rice"],
["reisen","to travel"],
["die Reise","journey / trip"],
["das Reisebüro","travel agency"],
["der Reiseführer","travel guide"],
["das Papier","paper"],
["die Papiere","documents / papers"],
["der Partner","partner"],
["die Partnerin","partner (female)"],
["die Party","party"],
["der Pass","passport"],
["die Pause","break / pause"],
["der Plan","plan"],
["der Platz","place / seat / square"],
["reparieren","to repair"],
["die Polizei","police"],
["die Reparatur","repair"],
["die Pommes","fries"],
["das Restaurant","restaurant"],
["die Post","post office / mail"],
["die Rezeption","reception"],
["die Postleitzahl","postal code"],
["richtig","correct / right"],
["das Praktikum","internship"],
["riechen","to smell"],
["die Praxis","doctor's office / practice"],
["ruhig","quiet / calm"],
["der Preis","price"],
["das Problem","problem"],
["der Prospekt","brochure"],
["die Prüfung","exam"],
["pünktlich","punctual / on time"],
["der Saft","juice"],
["sagen","to say"],
["der Salat","salad"],
["das Salz","salt"],
["die S-Bahn","city train"],
["der Schalter","counter / switch"],
["scheinen","to shine / seem"],
["rauchen","to smoke"],
["schicken","to send"],
["sein","to be"],
["das Schild","sign"],
["der Schinken","ham"],
["zu","to / too (much)"],
["schlafen","to sleep"],
["seit","since"],
["selbstständig","self-employed"],
["sitzen","to sit"],
["das Sofa","sofa"],
["sofort","immediately"],
["schlecht","bad"],
["schließen","to close"],
["geschlossen","closed"],
["der Schluss","end / conclusion"],
["der Schlüssel","key"],
["der Sohn","son"],
["schmecken","to taste (good)"],
["sollen","should / to be supposed to"],
["schnell","fast"],
["die Sonne","sun"],
["schon","already"],
["spät","late"],
["schön","beautiful / nice"],
["später","later"],
["die Speisekarte","menu"],
["spielen","to play"],
["der Schrank","cupboard / wardrobe"],
["schreiben","to write"],
["der Sport","sport"],
["der Schuh","shoe"],
["die Sprache","language"],
["die Schule","school"],
["sprechen","to speak"],
["der Schüler","pupil / student"],
["die Stadt","city"],
["schwer","heavy / difficult"],
["stehen","to stand"],
["die Schwester","sister"],
["die Stelle","position / job"],
["schwimmen","to swim"],
["stellen","to put / place"],
["das Schwimmbad","swimming pool"],
["der Stock","floor / story"],
["der See","lake"],
["sehen","to see"],
["die Sehenswürdigkeit","sight / attraction"],
["sehr","very"],
["die Straße","street"],
["die Straßenbahn","tram"],
["studieren","to study (university)"],
["das Studium","(university) studies"],
["tschüss","bye"],
["der Student","university student"],
["tun","to do"],
["die Stunde","hour / lesson"],
["suchen","to search / look for"],
["übernachten","to stay overnight"],
["überweisen","to transfer (money)"],
["tanzen","to dance"],
["die Uhr","clock / watch / o'clock"],
["die Tasche","bag"],
["um","at (time) / around"],
["das Taxi","taxi"],
["umziehen","to move (house)"],
["der Tee","tea"],
["und","and"],
["der Teil","part"],
["unten","below / downstairs"],
["telefonieren","to phone"],
["unter","under"],
["das Telefon","telephone"],
["der Unterricht","lesson / class"],
["der Termin","appointment"],
["unterschreiben","to sign"],
["der Test","test"],
["die Unterschrift","signature"],
["teuer","expensive"],
["der Urlaub","vacation"],
["der Text","text"],
["das Thema","topic"],
["der Vater","father"],
["das Ticket","ticket"],
["verboten","forbidden"],
["der Tisch","table"],
["verdienen","to earn"],
["die Tochter","daughter"],
["der Verein","club / association"],
["die Toilette","toilet"],
["verheiratet","married"],
["die Tomate","tomato"],
["verkaufen","to sell"],
["tot","dead"],
["der Verkäufer","salesperson"],
["treffen","to meet"],
["vermieten","to rent out"],
["die Treppe","stairs"],
["der Vermieter","landlord"],
["trinken","to drink"],
["verstehen","to understand"],
["der Verwandte","relative"],
["viel","much / a lot"],
["vielleicht","maybe"],
["von","from / of"],
["das Wiedersehen","goodbye / reunion"],
["wie viel","how much"],
["willkommen","welcome"],
["der Wind","wind"],
["vor","in front of / before"],
["wissen","to know (facts)"],
["der Vorname","first name"],
["die Vorsicht","caution"],
["wohnen","to live / reside"],
["vorstellen","to introduce"],
["die Wohnung","apartment / flat"],
["wollen","to want"],
["das Wort","word"],
["wunderbar","wonderful"],
["wandern","to hike"],
["warten","to wait"],
["was für ein","what kind of"],
["waschen","to wash"],
["das Wasser","water"],
["weh tun","to hurt"],
["weiblich","female"],
["der Wein","wine"],
["weit","far"],
["weiter","further / continue"],
["welcher","which"],
["die Welt","world"],
["wenig","little / few"],
["zahlen","to pay"],
["die Zeit","time"],
["zurzeit","currently"],
["die Zeitung","newspaper"],
["die Zigarette","cigarette"],
["das Zimmer","room"],
["der Zoll","customs"],
["zufrieden","satisfied"],
["der Zug","train"],
["werden","to become"],
["zurück","back"],
["das Wetter","weather"],
["zusammen","together"],
["wichtig","important"],
["zwischen","between"],
["wiederholen","to repeat"],
["das Wiederhören","goodbye (on the phone)"]
];
